"""Built-in help-book categories for the OODocs public API."""

from __future__ import annotations

from oodocs.apidoc.categories import ApiCategory, GuideLink


OODocs_API_CATEGORIES: tuple[ApiCategory, ...] = (
    ApiCategory(
        id="core-document-model",
        title="Core Document Model",
        summary="Create documents, configure settings, validate, and render outputs.",
        include=(
            "oodocs.Document",
            "oodocs.DocumentSettings",
            "oodocs.OutputBundle",
            "oodocs.ValidationResult",
            "oodocs.ValidationIssue",
            "oodocs.DocumentValidationError",
        ),
        order=10,
        guide_links=(GuideLink("Overview", "usage-guide.html#overview"),),
    ),
    ApiCategory(
        id="document-structure",
        title="Document Structure",
        summary="Create parts, chapters, sections, paragraphs, lists, boxes, and generated pages.",
        include=(
            "oodocs.Part",
            "oodocs.Chapter",
            "oodocs.Section",
            "oodocs.Subsection",
            "oodocs.SubSubsection",
            "oodocs.Paragraph",
            "oodocs.BulletList",
            "oodocs.NumberedList",
            "oodocs.Box",
            "oodocs.TableOfContents",
            "oodocs.ListOfTables",
            "oodocs.ListOfFigures",
            "oodocs.ReferenceList",
            "oodocs.CommentList",
            "oodocs.FootnoteList",
        ),
        order=20,
        guide_links=(GuideLink("Document Model", "usage-guide.html#document-model"),),
    ),
    ApiCategory(
        id="inline-content",
        title="Inline Content",
        summary="Style inline text, links, citations, references, chips, comments, footnotes, and math.",
        include=(
            "oodocs.Text",
            "oodocs.bold",
            "oodocs.italic",
            "oodocs.inline_code",
            "oodocs.text_color",
            "oodocs.highlight",
            "oodocs.link",
            "oodocs.reference",
            "oodocs.tag",
            "oodocs.badge",
            "oodocs.status",
            "oodocs.keyboard",
            "oodocs.Comment",
            "oodocs.Footnote",
            "oodocs.Math",
            "oodocs.Equation",
        ),
        order=30,
    ),
    ApiCategory(
        id="tables-figures",
        title="Tables and Figures",
        summary="Create structured tables, figures, image data, subfigures, and media references.",
        include=(
            "oodocs.Table",
            "oodocs.TableCell",
            "oodocs.TableCellStyle",
            "oodocs.Figure",
            "oodocs.ImageData",
            "oodocs.SubFigure",
            "oodocs.SubFigureGroup",
        ),
        order=40,
        guide_links=(
            GuideLink(
                "Tables, Figures, and Cross-References",
                "usage-guide.html#tables-figures",
            ),
        ),
    ),
    ApiCategory(
        id="layout-theme",
        title="Layout and Theme",
        summary="Configure page size, margins, typography, captions, generated pages, and document-wide defaults.",
        include=(
            "oodocs.PageSize",
            "oodocs.PageMargins",
            "oodocs.Theme",
            "oodocs.StyleSheet",
            "oodocs.TextStyle",
            "oodocs.ParagraphStyle",
            "oodocs.RunInTitleStyle",
            "oodocs.TableStyle",
            "oodocs.BoxStyle",
            "oodocs.ListStyle",
            "oodocs.HeadingNumbering",
            "oodocs.TocLevelStyle",
        ),
        order=50,
    ),
    ApiCategory(
        id="imports-workflows",
        title="Imports and Workflows",
        summary="Load, parse, validate, and render authored Python, Markdown, and notebook sources.",
        include=(
            "oodocs.parse_markdown",
            "oodocs.parse_markdown_file",
            "oodocs.from_markdown",
            "oodocs.from_markdown_file",
            "oodocs.parse_notebook",
            "oodocs.from_notebook",
            "oodocs.NotebookImportOptions",
            "oodocs.load_source_document",
            "oodocs.save_document_outputs",
            "oodocs.build_source_outputs",
            "oodocs.validate_source_document",
        ),
        order=60,
    ),
    ApiCategory(
        id="citations-authors",
        title="Citations and Authors",
        summary="Describe authors, affiliations, citation sources, and bibliography output.",
        include=(
            "oodocs.Author",
            "oodocs.Affiliation",
            "oodocs.AuthorLayout",
            "oodocs.CitationSource",
            "oodocs.CitationLibrary",
        ),
        order=70,
    ),
    ApiCategory(
        id="presets-adapters",
        title="Presets and Adapters",
        summary="Use ready-made components and repository artifact adapters.",
        include=(
            "oodocs.presets.CalloutBox",
            "oodocs.presets.KeyValueTable",
            "oodocs.presets.Nomenclature",
            "oodocs.adapters.ProjectMetadata",
            "oodocs.adapters.GithubWorkflowSummary",
            "oodocs.adapters.ReleaseManifestSummary",
            "oodocs.ReleaseEvidence",
            "oodocs.ReleaseEvidenceBundle",
        ),
        order=80,
    ),
    ApiCategory(
        id="apidoc",
        title="API Documentation Objects",
        summary="Collect Python API objects, query them, check documentation coverage, and insert selected API blocks into documents.",
        include=(
            "oodocs.apidoc.collect_api",
            "oodocs.apidoc.ApiPackage",
            "oodocs.apidoc.ApiModule",
            "oodocs.apidoc.ApiObject",
            "oodocs.apidoc.ApiParameter",
            "oodocs.apidoc.ApiCollectConfig",
            "oodocs.apidoc.ApiPresentationProfile",
            "oodocs.apidoc.check_api_docs",
            "oodocs.apidoc.diff_api",
        ),
        order=90,
    ),
)


__all__ = ["OODocs_API_CATEGORIES"]
