"""Built-in help-book categories for the OODocs public API."""

from __future__ import annotations

from oodocs.apidoc.categories import ApiCategory, GuideLink


OODocs_API_CATEGORIES: tuple[ApiCategory, ...] = (
    ApiCategory(
        id="core-document-model",
        title="Core Document Model",
        summary="Create documents, configure settings, validate, and render outputs.",
        include=(
            "oodocs.Document",
            "oodocs.DocumentMetadata",
            "oodocs.DocumentSettings",
            "oodocs.OODocsError",
            "oodocs.OutputBundle",
            "oodocs.ResultLike",
            "oodocs.ValidationResult",
            "oodocs.ValidationIssue",
            "oodocs.DocumentValidationError",
            "oodocs.document.*",
            "oodocs.core.*",
            "oodocs.validation.*",
        ),
        order=10,
        guide_links=(GuideLink("Overview", "usage-guide.html#overview"),),
    ),
    ApiCategory(
        id="document-structure",
        title="Document Structure",
        summary="Create parts, chapters, sections, paragraphs, lists, boxes, and generated pages.",
        include=(
            "oodocs.Part",
            "oodocs.Chapter",
            "oodocs.Section",
            "oodocs.Subsection",
            "oodocs.SubSubsection",
            "oodocs.MIN_SECTION_LEVEL",
            "oodocs.MAX_SECTION_LEVEL",
            "oodocs.Paragraph",
            "oodocs.CodeBlock",
            "oodocs.BulletList",
            "oodocs.NumberedList",
            "oodocs.Box",
            "oodocs.PageBreak",
            "oodocs.VerticalSpace",
            "oodocs.Divider",
            "oodocs.ColumnSpan",
            "oodocs.MultiColumn",
            "oodocs.section_for_level",
            "oodocs.shift_heading_level",
            "oodocs.shift_heading_levels",
            "oodocs.TableOfContents",
            "oodocs.ListOfTables",
            "oodocs.ListOfFigures",
            "oodocs.glossary.*",
            "oodocs.ReferenceList",
            "oodocs.CommentList",
            "oodocs.FootnoteList",
            "oodocs.engineering.Algorithm",
            "oodocs.structure.*",
            "oodocs.components.blocks.*",
            "oodocs.generated.*",
            "oodocs.components.generated.*",
            "oodocs.components.glossary.*",
            "oodocs.components.base.*",
            "oodocs.layout.indexing.*",
        ),
        order=20,
        guide_links=(GuideLink("Document Model", "usage-guide.html#document-model"),),
    ),
    ApiCategory(
        id="inline-content",
        title="Inline Content",
        summary="Style inline text, links, citations, references, chips, comments, footnotes, and math.",
        include=(
            "oodocs.Text",
            "oodocs.bold",
            "oodocs.italic",
            "oodocs.inline_code",
            "oodocs.text_color",
            "oodocs.highlight",
            "oodocs.link",
            "oodocs.url",
            "oodocs.Ref",
            "oodocs.ref",
            "oodocs.reference",
            "oodocs.refs",
            "oodocs.ref_range",
            "oodocs.paren_ref",
            "oodocs.page_ref",
            "oodocs.ReferenceFormat",
            "oodocs.cite",
            "oodocs.comment",
            "oodocs.review.todo",
            "oodocs.review.margin_note",
            "oodocs.footnote",
            "oodocs.math",
            "oodocs.styled",
            "oodocs.line_break",
            "oodocs.superscript",
            "oodocs.subscript",
            "oodocs.prescript",
            "oodocs.strikethrough",
            "oodocs.markup",
            "oodocs.tag",
            "oodocs.badge",
            "oodocs.status",
            "oodocs.keyboard",
            "oodocs.Comment",
            "oodocs.review.Todo",
            "oodocs.review.MarginNote",
            "oodocs.Footnote",
            "oodocs.InlineChip",
            "oodocs.LineBreak",
            "oodocs.Math",
            "oodocs.Equation",
            "oodocs.engineering.AlignedEquation",
            "oodocs.engineering.CasesEquation",
            "oodocs.engineering.ChemicalFormula",
            "oodocs.engineering.ReactionEquation",
            "oodocs.engineering.ce",
            "oodocs.engineering.chemical_formula",
            "oodocs.chem.*",
            "oodocs.review.*",
            "oodocs.components.inline.*",
            "oodocs.components.chemistry.*",
            "oodocs.components.markup.*",
            "oodocs.components.equations.*",
        ),
        order=30,
    ),
    ApiCategory(
        id="tables-figures",
        title="Tables and Figures",
        summary="Create structured tables, figures, image data, subfigures, subtables, and media references.",
        include=(
            "oodocs.Table",
            "oodocs.TableCell",
            "oodocs.ColumnSpec",
            "oodocs.TableCellStyle",
            "oodocs.Figure",
            "oodocs.CropBox",
            "oodocs.ImageData",
            "oodocs.PdfPages",
            "oodocs.SubFigure",
            "oodocs.SubFigureGroup",
            "oodocs.SubTable",
            "oodocs.SubTableGroup",
            "oodocs.positioning.*",
            "oodocs.components.media.*",
            "oodocs.components.positioning.*",
        ),
        order=40,
        guide_links=(
            GuideLink(
                "Tables, Figures, and Cross-References",
                "usage-guide.html#tables-figures",
            ),
        ),
    ),
    ApiCategory(
        id="layout-theme",
        title="Layout and Theme",
        summary="Configure page size, margins, typography, captions, generated pages, and document-wide defaults.",
        include=(
            "oodocs.PageSize",
            "oodocs.PageMargins",
            "oodocs.PageLayout",
            "oodocs.Theme",
            "oodocs.StyleSheet",
            "oodocs.BorderStyle",
            "oodocs.Padding",
            "oodocs.CounterStyle",
            "oodocs.StrokeStyle",
            "oodocs.TextStyle",
            "oodocs.ParagraphStyle",
            "oodocs.RunInTitleStyle",
            "oodocs.TableStyle",
            "oodocs.BoxStyle",
            "oodocs.InlineChipStyle",
            "oodocs.ListStyle",
            "oodocs.HeadingStyle",
            "oodocs.HeadingNumbering",
            "oodocs.TocLevelStyle",
            "oodocs.TypographyDefaults",
            "oodocs.CaptionDefaults",
            "oodocs.CitationDefaults",
            "oodocs.LinkDefaults",
            "oodocs.FootnoteDefaults",
            "oodocs.FootnoteStyle",
            "oodocs.GeneratedContentDefaults",
            "oodocs.LocaleDefaults",
            "oodocs.PageNumberDefaults",
            "oodocs.HeaderFooterDefaults",
            "oodocs.TitleMatterDefaults",
            "oodocs.BlockDefaults",
            "oodocs.settings.*",
            "oodocs.styles.*",
            "oodocs.layout.*",
        ),
        order=50,
    ),
    ApiCategory(
        id="imports-workflows",
        title="Imports and Workflows",
        summary="Load, parse, validate, and render authored Python, Markdown, and notebook sources.",
        include=(
            "oodocs.OutputFormat",
            "oodocs.OUTPUT_FORMATS",
            "oodocs.parse_markdown",
            "oodocs.parse_markdown_file",
            "oodocs.from_markdown",
            "oodocs.from_markdown_file",
            "oodocs.parse_notebook",
            "oodocs.from_notebook",
            "oodocs.ImportIssue",
            "oodocs.ImportPolicyError",
            "oodocs.ImportResult",
            "oodocs.NotebookImportOptions",
            "oodocs.load_source_document",
            "oodocs.load_document_from_python",
            "oodocs.save_document_outputs",
            "oodocs.build_source_outputs",
            "oodocs.validate_source_document",
            "oodocs.compatibility.*",
            "oodocs.importers.*",
            "oodocs.workflows.*",
        ),
        order=60,
    ),
    ApiCategory(
        id="citations-authors",
        title="Citations and Authors",
        summary="Describe authors, affiliations, citation sources, and bibliography output.",
        include=(
            "oodocs.Author",
            "oodocs.Affiliation",
            "oodocs.AuthorLayout",
            "oodocs.CitationSource",
            "oodocs.CitationLibrary",
            "oodocs.components.people.*",
            "oodocs.components.references.*",
        ),
        order=70,
    ),
    ApiCategory(
        id="presets-adapters",
        title="Presets and Adapters",
        summary="Use ready-made components and repository artifact adapters.",
        include=(
            "oodocs.presets.CalloutBox",
            "oodocs.presets.KeyValueTable",
            "oodocs.presets.Nomenclature",
            "oodocs.presets.CoverPagePreset",
            "oodocs.presets.TechnicalReportTemplate",
            "oodocs.presets.SoftwareManualTemplate",
            "oodocs.presets.BookTemplate",
            "oodocs.adapters.ProjectMetadata",
            "oodocs.adapters.GithubWorkflowSummary",
            "oodocs.adapters.ReleaseManifestSummary",
            "oodocs.ReleaseEvidence",
            "oodocs.ReleaseEvidenceBundle",
            "oodocs.presets.*",
            "oodocs.adapters.*",
        ),
        order=80,
    ),
    ApiCategory(
        id="apidoc",
        title="API Documentation Objects",
        summary="Collect Python API objects, query them, check documentation coverage, and insert selected API blocks into documents.",
        include=(
            "oodocs.apidoc.collect_api",
            "oodocs.apidoc.ApiPackage",
            "oodocs.apidoc.ApiModule",
            "oodocs.apidoc.ApiObject",
            "oodocs.apidoc.ApiParameter",
            "oodocs.apidoc.ApiCollectConfig",
            "oodocs.apidoc.ApiPresentationProfile",
            "oodocs.apidoc.check_api_docs",
            "oodocs.apidoc.diff_api",
            "oodocs.apidoc.*",
        ),
        order=90,
    ),
    ApiCategory(
        id="renderer-extension-api",
        title="Renderer Extension API",
        summary="Renderer protocol objects used by custom renderer integrations.",
        include=("oodocs.renderers.*",),
        order=100,
        show_in_help_book=False,
    ),
    ApiCategory(
        id="command-entrypoints",
        title="Command Entrypoints",
        summary="Console entrypoint functions used by installed commands.",
        include=("oodocs.cli.*", "oodocs.evidence.*"),
        order=110,
        show_in_help_book=False,
    ),
    ApiCategory(
        id="public-api-policy",
        title="Public API Policy",
        summary="Internal public API tier metadata used by compatibility tests.",
        include=("oodocs.public_api.*",),
        order=120,
        show_in_help_book=False,
    ),
)


__all__ = ["OODocs_API_CATEGORIES"]
