"""Top-level package for oodocs."""

from importlib.metadata import PackageNotFoundError, version as package_version

from oodocs.core import OODocsError
from oodocs.compatibility import OUTPUT_FORMATS, OutputFormat
from oodocs.components.blocks import (
    Assumption,
    Axiom,
    Box,
    BulletList,
    Chapter,
    Claim,
    CodeBlock,
    ColumnSpan,
    Conjecture,
    CountableBlock,
    Corollary,
    Definition,
    Divider,
    Equation,
    Example,
    MAX_SECTION_LEVEL,
    MIN_SECTION_LEVEL,
    Lemma,
    MultiColumn,
    NumberedList,
    PageBreak,
    Paragraph,
    Part,
    Proof,
    Proposition,
    Remark,
    Section,
    Subsection,
    Subsubsection,
    Theorem,
    VerticalSpace,
    countable_kind,
    section_for_level,
    shift_heading_level,
    shift_heading_levels,
)
from oodocs.components.generated import (
    CommentsPage,
    FigureList,
    ReferencesPage,
    TableList,
    TableOfContents,
    TocLevelStyle,
)
from oodocs.components.media import (
    Figure,
    ImageData,
    SubFigure,
    SubFigureGroup,
    Table,
    TableCell,
    TableCellStyle,
)
from oodocs.components.markup import markup
from oodocs.components.people import Affiliation, Author, AuthorLayout
from oodocs.components.references import CitationLibrary, CitationSource
from oodocs.components.positioning import ImageBox, Shape, TextBox
from oodocs.document import Document
from oodocs.importers.markdown import (
    from_markdown,
    from_markdown_file,
    parse_markdown,
    parse_markdown_file,
)
from oodocs.importers.notebook import (
    NotebookImportOptions,
    from_ipynb,
    from_notebook,
    parse_ipynb,
    parse_notebook,
)
from oodocs.importers.results import ImportIssue, ImportPolicyError, ImportResult
from oodocs.components.inline import (
    Comment,
    Footnote,
    InlineChip,
    InlineChipStyle,
    LineBreak,
    Math,
    Text,
    badge,
    bold,
    code,
    color,
    cite,
    comment,
    footnote,
    highlight,
    italic,
    keyboard,
    link,
    line_break,
    math,
    prescript,
    reference,
    status,
    strike,
    strikethrough,
    styled,
    subscript,
    superscript,
    tag,
)
from oodocs.settings import (
    BlockOptions,
    BoxStyle,
    CaptionOptions,
    CitationOptions,
    DocumentSettings,
    GeneratedPageOptions,
    HeadingNumbering,
    ListStyle,
    PageNumberOptions,
    PageMargins,
    PageSize,
    ParagraphStyle,
    ParagraphTitleStyle,
    TableStyle,
    TextStyle,
    TitleMatterOptions,
    TypographyOptions,
    Theme,
)
from oodocs.validation import DocumentValidationError, ValidationIssue, ValidationResult
from oodocs.workflows import (
    RenderedOutputs,
    build_python_document,
    convert_source,
    load_document,
    load_python_document,
    render_document,
    validate_source,
)


_FALLBACK_VERSION = "1.0.4"


def _resolve_version() -> str:
    try:
        return package_version("oodocs")
    except PackageNotFoundError:
        try:
            from setuptools_scm import get_version
        except ImportError:
            return _FALLBACK_VERSION
        return get_version(
            root="../..",
            relative_to=__file__,
            fallback_version=_FALLBACK_VERSION,
            tag_regex=r"^v(?P<version>\d+\.\d+\.\d+)$",
        )


__version__ = _resolve_version()

__all__ = [
    "Affiliation",
    "Assumption",
    "Author",
    "AuthorLayout",
    "Axiom",
    "BlockOptions",
    "Box",
    "BoxStyle",
    "BulletList",
    "CaptionOptions",
    "CitationOptions",
    "CitationLibrary",
    "CitationSource",
    "Chapter",
    "Claim",
    "Comment",
    "CommentsPage",
    "CodeBlock",
    "ColumnSpan",
    "Conjecture",
    "CountableBlock",
    "Corollary",
    "Definition",
    "Document",
    "DocumentSettings",
    "OODocsError",
    "Divider",
    "Equation",
    "Example",
    "Figure",
    "FigureList",
    "Footnote",
    "GeneratedPageOptions",
    "HeadingNumbering",
    "ImageBox",
    "ImageData",
    "ImportIssue",
    "ImportPolicyError",
    "ImportResult",
    "InlineChip",
    "InlineChipStyle",
    "LineBreak",
    "ListStyle",
    "Lemma",
    "Math",
    "MAX_SECTION_LEVEL",
    "MIN_SECTION_LEVEL",
    "MultiColumn",
    "NotebookImportOptions",
    "NumberedList",
    "OUTPUT_FORMATS",
    "OutputFormat",
    "PageNumberOptions",
    "PageMargins",
    "PageSize",
    "PageBreak",
    "Paragraph",
    "Part",
    "Proof",
    "Proposition",
    "ParagraphStyle",
    "ParagraphTitleStyle",
    "ReferencesPage",
    "RenderedOutputs",
    "Remark",
    "Section",
    "Shape",
    "SubFigure",
    "SubFigureGroup",
    "Subsection",
    "Subsubsection",
    "Table",
    "TableCell",
    "TableCellStyle",
    "TableStyle",
    "TableOfContents",
    "TableList",
    "Text",
    "TextBox",
    "TextStyle",
    "Theorem",
    "TitleMatterOptions",
    "Theme",
    "TocLevelStyle",
    "TypographyOptions",
    "DocumentValidationError",
    "ValidationIssue",
    "ValidationResult",
    "VerticalSpace",
    "__version__",
    "badge",
    "bold",
    "build_python_document",
    "code",
    "color",
    "cite",
    "comment",
    "countable_kind",
    "convert_source",
    "footnote",
    "from_ipynb",
    "from_markdown",
    "from_markdown_file",
    "from_notebook",
    "highlight",
    "italic",
    "keyboard",
    "link",
    "line_break",
    "load_document",
    "load_python_document",
    "math",
    "prescript",
    "reference",
    "render_document",
    "status",
    "strike",
    "strikethrough",
    "markup",
    "styled",
    "parse_ipynb",
    "parse_markdown",
    "parse_markdown_file",
    "parse_notebook",
    "section_for_level",
    "shift_heading_level",
    "shift_heading_levels",
    "subscript",
    "superscript",
    "tag",
    "validate_source",
]

for _module_name in ("components", "core", "document", "layout", "settings"):
    globals().pop(_module_name, None)

del _resolve_version
del _module_name
