"""Top-level package for oodocs."""

from importlib.metadata import PackageNotFoundError, version as package_version

from oodocs.core import OODocsError
from oodocs.compatibility import OUTPUT_FORMATS, OutputFormat
from oodocs.components.blocks import (
    Assumption,
    Axiom,
    Box,
    BulletList,
    Chapter,
    Claim,
    CodeBlock,
    ColumnSpan,
    Conjecture,
    CountableBlock,
    Corollary,
    Definition,
    Divider,
    Equation,
    Example,
    MAX_SECTION_LEVEL,
    MIN_SECTION_LEVEL,
    Lemma,
    MultiColumn,
    NumberedList,
    PageBreak,
    Paragraph,
    Part,
    Proof,
    Proposition,
    Remark,
    Section,
    Subsection,
    SubSubsection,
    Theorem,
    VerticalSpace,
    create_countable_block_type,
    section_for_level,
    shift_heading_level,
    shift_heading_levels,
)
from oodocs.components.generated import (
    CommentList,
    FootnoteList,
    ListOfFigures,
    ReferenceList,
    ListOfTables,
    TableOfContents,
    TocLevelStyle,
)
from oodocs.components.media import (
    Figure,
    ImageData,
    SubFigure,
    SubFigureGroup,
    Table,
    TableCell,
)
from oodocs.components.markup import markup
from oodocs.components.people import Affiliation, Author, AuthorLayout
from oodocs.components.references import CitationLibrary, CitationSource
from oodocs.components.positioning import ImageBox, Shape, TextBox
from oodocs.document import Document
from oodocs.importers.markdown import (
    from_markdown,
    from_markdown_file,
    parse_markdown,
    parse_markdown_file,
)
from oodocs.importers.notebook import (
    NotebookImportOptions,
    from_notebook,
    parse_notebook,
)
from oodocs.importers.results import ImportIssue, ImportPolicyError, ImportResult
from oodocs.components.inline import (
    Comment,
    Footnote,
    InlineChip,
    LineBreak,
    Math,
    Text,
    badge,
    bold,
    cite,
    comment,
    footnote,
    highlight,
    inline_code,
    italic,
    keyboard,
    link,
    line_break,
    math,
    prescript,
    reference,
    status,
    strikethrough,
    styled,
    subscript,
    superscript,
    tag,
    text_color,
)
from oodocs.settings import (
    DocumentSettings,
    PageMargins,
    PageSize,
)
from oodocs.styles import (
    BlockDefaults,
    BorderStyle,
    BoxStyle,
    CaptionDefaults,
    CitationDefaults,
    GeneratedContentDefaults,
    HeadingNumbering,
    InlineChipStyle,
    ListStyle,
    PageNumberDefaults,
    Padding,
    ParagraphStyle,
    RunInTitleStyle,
    TableCellStyle,
    TableStyle,
    TextStyle,
    TitleMatterDefaults,
    TypographyDefaults,
    Theme,
)
from oodocs.validation import DocumentValidationError, ValidationIssue, ValidationResult
from oodocs.workflows import (
    OutputBundle,
    build_source_outputs,
    load_source_document,
    load_document_from_python,
    save_document_outputs,
    validate_source_document,
)


_FALLBACK_VERSION = "1.0.4"


def _resolve_version() -> str:
    try:
        return package_version("oodocs")
    except PackageNotFoundError:
        try:
            from setuptools_scm import get_version
        except ImportError:
            return _FALLBACK_VERSION
        return get_version(
            root="../..",
            relative_to=__file__,
            fallback_version=_FALLBACK_VERSION,
            tag_regex=r"^v(?P<version>\d+\.\d+\.\d+)$",
        )


__version__ = _resolve_version()

__all__ = [
    "Affiliation",
    "Assumption",
    "Author",
    "AuthorLayout",
    "Axiom",
    "BlockDefaults",
    "BorderStyle",
    "Box",
    "BoxStyle",
    "BulletList",
    "CaptionDefaults",
    "CitationDefaults",
    "CitationLibrary",
    "CitationSource",
    "Chapter",
    "Claim",
    "Comment",
    "CommentList",
    "CodeBlock",
    "ColumnSpan",
    "Conjecture",
    "CountableBlock",
    "Corollary",
    "Definition",
    "Document",
    "DocumentSettings",
    "OODocsError",
    "Divider",
    "Equation",
    "Example",
    "Figure",
    "ListOfFigures",
    "Footnote",
    "FootnoteList",
    "GeneratedContentDefaults",
    "HeadingNumbering",
    "ImageBox",
    "ImageData",
    "ImportIssue",
    "ImportPolicyError",
    "ImportResult",
    "InlineChip",
    "InlineChipStyle",
    "LineBreak",
    "ListStyle",
    "Lemma",
    "Math",
    "MAX_SECTION_LEVEL",
    "MIN_SECTION_LEVEL",
    "MultiColumn",
    "NotebookImportOptions",
    "NumberedList",
    "OUTPUT_FORMATS",
    "OutputFormat",
    "PageNumberDefaults",
    "Padding",
    "PageMargins",
    "PageSize",
    "PageBreak",
    "Paragraph",
    "Part",
    "Proof",
    "Proposition",
    "ParagraphStyle",
    "RunInTitleStyle",
    "ReferenceList",
    "OutputBundle",
    "Remark",
    "Section",
    "Shape",
    "SubFigure",
    "SubFigureGroup",
    "Subsection",
    "SubSubsection",
    "Table",
    "TableCell",
    "TableCellStyle",
    "TableStyle",
    "TableOfContents",
    "ListOfTables",
    "Text",
    "TextBox",
    "TextStyle",
    "Theorem",
    "TitleMatterDefaults",
    "Theme",
    "TocLevelStyle",
    "TypographyDefaults",
    "DocumentValidationError",
    "ValidationIssue",
    "ValidationResult",
    "VerticalSpace",
    "__version__",
    "badge",
    "bold",
    "build_source_outputs",
    "cite",
    "comment",
    "create_countable_block_type",
    "footnote",
    "from_markdown",
    "from_markdown_file",
    "from_notebook",
    "highlight",
    "inline_code",
    "italic",
    "keyboard",
    "link",
    "line_break",
    "load_source_document",
    "load_document_from_python",
    "math",
    "prescript",
    "reference",
    "save_document_outputs",
    "status",
    "strikethrough",
    "markup",
    "styled",
    "parse_markdown",
    "parse_markdown_file",
    "parse_notebook",
    "section_for_level",
    "shift_heading_level",
    "shift_heading_levels",
    "subscript",
    "superscript",
    "tag",
    "text_color",
    "validate_source_document",
]

for _module_name in ("components", "core", "document", "layout", "settings"):
    globals().pop(_module_name, None)

del _resolve_version
del _module_name
