"""Top-level package for oodocs."""

from importlib.metadata import PackageNotFoundError, version as package_version

from oodocs.core import OODocsError
from oodocs.compatibility import OUTPUT_FORMATS, OutputFormat
from oodocs.components.blocks import (
    Box,
    BulletList,
    Chapter,
    CodeBlock,
    ColumnSpan,
    Divider,
    Equation,
    MAX_SECTION_LEVEL,
    MIN_SECTION_LEVEL,
    MultiColumn,
    NumberedList,
    PageBreak,
    Paragraph,
    Part,
    Section,
    Subsection,
    SubSubsection,
    VerticalSpace,
    section_for_level,
    shift_heading_level,
    shift_heading_levels,
)
from oodocs.components.generated import (
    CommentList,
    FootnoteList,
    ListOfFigures,
    ReferenceList,
    ListOfTables,
    TableOfContents,
    TocLevelStyle,
)
from oodocs.components.media import (
    Figure,
    ImageData,
    SubFigure,
    SubFigureGroup,
    Table,
    TableCell,
)
from oodocs.components.markup import markup
from oodocs.components.people import Affiliation, Author, AuthorLayout
from oodocs.components.references import CitationLibrary, CitationSource
from oodocs.document import Document
from oodocs.importers.results import ImportIssue, ImportPolicyError, ImportResult
from oodocs.components.inline import (
    Comment,
    Footnote,
    InlineChip,
    LineBreak,
    Math,
    Text,
    badge,
    bold,
    cite,
    comment,
    footnote,
    highlight,
    inline_code,
    italic,
    keyboard,
    link,
    line_break,
    math,
    prescript,
    ref,
    ref_range,
    refs,
    status,
    strikethrough,
    styled,
    subscript,
    superscript,
    tag,
    text_color,
    url,
)
from oodocs.settings import (
    DocumentMetadata,
    DocumentSettings,
    PageLayout,
    PageMargins,
    PageSize,
)
from oodocs.styles import (
    BlockDefaults,
    BorderStyle,
    BoxStyle,
    CaptionDefaults,
    CitationDefaults,
    CounterStyle,
    FootnoteDefaults,
    FootnoteStyle,
    GeneratedContentDefaults,
    HeaderFooterDefaults,
    HeadingStyle,
    HeadingNumbering,
    InlineChipStyle,
    LinkDefaults,
    ListStyle,
    LocaleDefaults,
    PageNumberDefaults,
    Padding,
    ParagraphStyle,
    RunInTitleStyle,
    StrokeStyle,
    StyleSheet,
    TableCellStyle,
    TableStyle,
    TextStyle,
    TitleMatterDefaults,
    TypographyDefaults,
    Theme,
)
from oodocs.validation import (
    DocumentValidationError,
    ResultLike,
    ValidationIssue,
    ValidationResult,
)
from oodocs.workflows import OutputBundle


_FALLBACK_VERSION = "1.1.0"


def _resolve_version() -> str:
    try:
        return package_version("oodocs")
    except PackageNotFoundError:
        try:
            from setuptools_scm import get_version
        except ImportError:
            return _FALLBACK_VERSION
        return get_version(
            root="../..",
            relative_to=__file__,
            fallback_version=_FALLBACK_VERSION,
            tag_regex=r"^v(?P<version>\d+\.\d+\.\d+)$",
        )


__version__ = _resolve_version()

__all__ = [
    "Affiliation",
    "Author",
    "AuthorLayout",
    "BlockDefaults",
    "BorderStyle",
    "Box",
    "BoxStyle",
    "BulletList",
    "CaptionDefaults",
    "CitationDefaults",
    "CounterStyle",
    "CitationLibrary",
    "CitationSource",
    "Chapter",
    "Comment",
    "CommentList",
    "CodeBlock",
    "ColumnSpan",
    "Document",
    "DocumentMetadata",
    "DocumentSettings",
    "OODocsError",
    "Divider",
    "Equation",
    "Figure",
    "ListOfFigures",
    "Footnote",
    "FootnoteDefaults",
    "FootnoteList",
    "FootnoteStyle",
    "GeneratedContentDefaults",
    "HeaderFooterDefaults",
    "HeadingStyle",
    "HeadingNumbering",
    "ImageData",
    "ImportIssue",
    "ImportPolicyError",
    "ImportResult",
    "InlineChip",
    "InlineChipStyle",
    "LineBreak",
    "LinkDefaults",
    "LocaleDefaults",
    "ListStyle",
    "Math",
    "MAX_SECTION_LEVEL",
    "MIN_SECTION_LEVEL",
    "MultiColumn",
    "NumberedList",
    "OUTPUT_FORMATS",
    "OutputFormat",
    "PageNumberDefaults",
    "Padding",
    "PageLayout",
    "PageMargins",
    "PageSize",
    "PageBreak",
    "Paragraph",
    "Part",
    "ParagraphStyle",
    "RunInTitleStyle",
    "ReferenceList",
    "ResultLike",
    "OutputBundle",
    "Section",
    "StrokeStyle",
    "StyleSheet",
    "SubFigure",
    "SubFigureGroup",
    "Subsection",
    "SubSubsection",
    "Table",
    "TableCell",
    "TableCellStyle",
    "TableStyle",
    "TableOfContents",
    "ListOfTables",
    "Text",
    "TextStyle",
    "TitleMatterDefaults",
    "Theme",
    "TocLevelStyle",
    "TypographyDefaults",
    "DocumentValidationError",
    "ValidationIssue",
    "ValidationResult",
    "VerticalSpace",
    "__version__",
    "badge",
    "bold",
    "cite",
    "comment",
    "footnote",
    "highlight",
    "inline_code",
    "italic",
    "keyboard",
    "link",
    "line_break",
    "math",
    "prescript",
    "ref",
    "ref_range",
    "refs",
    "status",
    "strikethrough",
    "markup",
    "styled",
    "section_for_level",
    "shift_heading_level",
    "shift_heading_levels",
    "subscript",
    "superscript",
    "tag",
    "text_color",
    "url",
]

for _module_name in ("components", "core", "document", "layout", "settings"):
    globals().pop(_module_name, None)

del _resolve_version
del _module_name
